// Pose library — pure data + pure functions. No Three.js, no DOM (Node-importable).
//
// Conventions:
//  - Character faces +Z at root.ry = 0. Character's left side is +X.
//  - A pose is { root: {x, y, z, ry}, joints: { name: {x, y, z} } } with Euler XYZ radians.
//    root.x/z are small in-stance offsets (embusen placement is applied separately);
//    root.y is an offset from standing hip height (negative = lower stance).
//  - Joint zero = standing straight, arms hanging at sides.
//  - Rotation signs: joint +x rotates the hanging limb backward (-Z), -x forward (+Z);
//    knee flexion is +x; elbow flexion is -x.

export const JOINT_NAMES = [
  'hips', 'spine', 'chest', 'neck', 'head',
  'shoulderL', 'elbowL', 'wristL', 'shoulderR', 'elbowR', 'wristR',
  'hipL', 'kneeL', 'ankleL', 'hipR', 'kneeR', 'ankleR',
];

export function emptyPose() {
  const joints = {};
  for (const n of JOINT_NAMES) joints[n] = { x: 0, y: 0, z: 0 };
  return { root: { x: 0, y: 0, z: 0, ry: 0 }, joints };
}

export const BASE_POSE = emptyPose();

// Merge partial poses left-to-right onto a fresh base. Later partials override
// per joint (whole-joint replacement) and per root field.
export function composePose(...partials) {
  const out = emptyPose();
  for (const p of partials) {
    if (!p) continue;
    if (p.root) for (const k of ['x', 'y', 'z', 'ry']) {
      if (p.root[k] !== undefined) out.root[k] = p.root[k];
    }
    if (p.joints) for (const [name, rot] of Object.entries(p.joints)) {
      out.joints[name] = { x: rot.x ?? 0, y: rot.y ?? 0, z: rot.z ?? 0 };
    }
  }
  return out;
}

// Mirror a partial pose across the sagittal plane: swap L/R joints,
// negate y/z rotation components, negate root.x and root.ry.
export function mirrorPose(p) {
  const out = { };
  if (p.root) out.root = {
    ...(p.root.x !== undefined ? { x: -p.root.x } : {}),
    ...(p.root.y !== undefined ? { y: p.root.y } : {}),
    ...(p.root.z !== undefined ? { z: p.root.z } : {}),
    ...(p.root.ry !== undefined ? { ry: -p.root.ry } : {}),
  };
  if (p.joints) {
    out.joints = {};
    for (const [name, rot] of Object.entries(p.joints)) {
      const swapped = name.endsWith('L') ? name.slice(0, -1) + 'R'
        : name.endsWith('R') ? name.slice(0, -1) + 'L' : name;
      out.joints[swapped] = { x: rot.x ?? 0, y: -(rot.y ?? 0), z: -(rot.z ?? 0) };
    }
  }
  return out;
}

const J = (joints, root) => ({ joints, ...(root ? { root } : {}) });

// ---------------------------------------------------------------------------
// Stances (authored left-lead where applicable; right-lead generated by mirror)
// ---------------------------------------------------------------------------
const STANCES_BASE = {
  ready: J({
    hipL: { z: 0.06 }, hipR: { z: -0.06 },
    shoulderL: { x: -0.12, z: 0.10 }, shoulderR: { x: -0.12, z: -0.10 },
    elbowL: { x: -0.25 }, elbowR: { x: -0.25 },
  }),
  bow: J({
    spine: { x: 0.35 }, chest: { x: 0.18 }, neck: { x: 0.12 },
    hipL: { z: 0.04 }, hipR: { z: -0.04 },
    shoulderL: { x: -0.05 }, shoulderR: { x: -0.05 },
  }),
  feetTogether: J({}),

  // Left foot forward Seisan-dachi
  seisanDachiL: J({
    hipL: { x: -0.42, z: 0.05 }, kneeL: { x: 0.38 }, ankleL: { x: 0.06 },
    hipR: { x: 0.28, z: -0.05 }, kneeR: { x: 0.10 }, ankleR: { x: -0.16 },
    spine: { x: 0.03 },
  }, { y: -0.06, z: 0.06 }),

  // Rooted hourglass stance (symmetric)
  seiunchinDachi: J({
    hipL: { x: -0.10, z: 0.32, y: 0.25 }, kneeL: { x: 0.55 }, ankleL: { x: -0.18 },
    hipR: { x: -0.10, z: -0.32, y: -0.25 }, kneeR: { x: 0.55 }, ankleR: { x: -0.18 },
  }, { y: -0.15 }),

  // Side-facing horse stance (symmetric)
  naihanchiDachi: J({
    hipL: { z: 0.30 }, kneeL: { x: 0.38 }, ankleL: { x: -0.14 },
    hipR: { z: -0.30 }, kneeR: { x: 0.38 }, ankleR: { x: -0.14 },
  }, { y: -0.11 }),

  // Left foot forward cat stance (weight back)
  catL: J({
    hipL: { x: -0.30 }, kneeL: { x: 0.60 }, ankleL: { x: 0.42 },
    hipR: { x: 0.10, z: -0.08 }, kneeR: { x: 0.42 }, ankleR: { x: -0.20 },
    spine: { x: 0.02 },
  }, { y: -0.10, z: -0.04 }),

  // Left foot forward T-stance (upright, side-on guard)
  tStanceL: J({
    hipL: { x: -0.22 }, kneeL: { x: 0.30 }, ankleL: { x: 0.12 },
    hipR: { x: 0.08, z: -0.10 }, kneeR: { x: 0.28 }, ankleR: { x: -0.12 },
    chest: { y: 0.35 },
  }, { y: -0.06 }),

  // Chinto stance, left lead: one-leg loaded, angled
  chintoL: J({
    hipL: { x: -0.34 }, kneeL: { x: 0.52 }, ankleL: { x: 0.28 },
    hipR: { x: 0.14, z: -0.10 }, kneeR: { x: 0.50 }, ankleR: { x: -0.22 },
    spine: { x: 0.04 }, chest: { y: 0.2 },
  }, { y: -0.11 }),

  // Kneeling: left knee down, right leg forward (Chinto finish)
  kneelL: J({
    hipL: { x: 0.10 }, kneeL: { x: 1.65 }, ankleL: { x: 0.6 },
    hipR: { x: -1.15 }, kneeR: { x: 1.25 }, ankleR: { x: 0.2 },
    spine: { x: 0.05 },
  }, { y: -0.42 }),

  // Crossover: left foot crossing in front toward the right
  crossoverL: J({
    hipL: { x: -0.20, z: -0.28 }, kneeL: { x: 0.30 },
    hipR: { x: 0.05, z: 0.10 }, kneeR: { x: 0.18 },
  }, { y: -0.05 }),
};

// ---------------------------------------------------------------------------
// Arm techniques (authored for RIGHT arm; left generated by mirror)
// suffix-less names here get R appended below.
// ---------------------------------------------------------------------------
const ARMS_RIGHT = {
  chamber: J({ shoulderR: { x: 0.40 }, elbowR: { x: -1.90 } }),
  punchMid: J({ shoulderR: { x: -1.30 }, elbowR: { x: -0.10 }, chest: { y: 0.18 } }),
  punchHigh: J({ shoulderR: { x: -1.55 }, elbowR: { x: -0.12 }, chest: { y: 0.18 } }),
  uppercut: J({ shoulderR: { x: -0.85 }, elbowR: { x: -1.45 }, chest: { y: 0.22 } }),
  backfist: J({ shoulderR: { x: -1.25, z: 0.55 }, elbowR: { x: -0.55 }, chest: { y: 0.12 } }),
  hammerfist: J({ shoulderR: { x: -1.05, z: 0.35 }, elbowR: { x: -0.85 } }),
  nukite: J({ shoulderR: { x: -1.35 }, elbowR: { x: -0.05 }, chest: { y: 0.2 } }),
  haito: J({ shoulderR: { x: -1.15, y: 0.55 }, elbowR: { x: -0.45 }, chest: { y: 0.1 } }),
  shutoLow: J({ shoulderR: { x: -0.55, z: 0.28 }, elbowR: { x: -0.35 } }),
  shutoMid: J({ shoulderR: { x: -1.05, y: 0.3 }, elbowR: { x: -0.55 } }),
  shote: J({ shoulderR: { x: -1.25 }, elbowR: { x: -0.25 }, wristR: { x: -0.5 } }),
  elbowStrike: J({ shoulderR: { x: -1.25 }, elbowR: { x: -2.45 }, chest: { y: 0.35 } }),
  elbowRising: J({ shoulderR: { x: -1.85 }, elbowR: { x: -2.50 } }),
  blockLow: J({ shoulderR: { x: -0.50, z: 0.22 }, elbowR: { x: -0.45 } }),
  blockMid: J({ shoulderR: { x: -1.00, z: 0.18 }, elbowR: { x: -1.25, y: 0.35 } }),
  blockHigh: J({ shoulderR: { x: -1.85, z: 0.25 }, elbowR: { x: -1.15 } }),
  guardChest: J({ shoulderR: { x: -0.70, y: 0.55 }, elbowR: { x: -1.55 } }),
  grabPull: J({ shoulderR: { x: -0.45 }, elbowR: { x: -1.35 }, chest: { y: -0.15 } }),
  openHandBlock: J({ shoulderR: { x: -1.10, z: 0.30 }, elbowR: { x: -0.85 }, wristR: { x: -0.3 } }),
};

// ---------------------------------------------------------------------------
// Two-arm poses (symmetric or fixed)
// ---------------------------------------------------------------------------
const ARMS_BOTH = {
  blockDoubleHigh: J({
    shoulderL: { x: -1.85, z: -0.30 }, elbowL: { x: -1.10 },
    shoulderR: { x: -1.85, z: 0.30 }, elbowR: { x: -1.10 },
  }),
  blockDoubleLow: J({
    shoulderL: { x: -0.55, z: -0.35 }, elbowL: { x: -0.30 },
    shoulderR: { x: -0.55, z: 0.35 }, elbowR: { x: -0.30 },
  }),
  xBlockLow: J({
    shoulderL: { x: -0.75, z: 0.35 }, elbowL: { x: -0.35 },
    shoulderR: { x: -0.75, z: -0.35 }, elbowR: { x: -0.35 },
    spine: { x: 0.12 },
  }),
  handsStacked: J({
    shoulderL: { x: -0.85, y: -0.5 }, elbowL: { x: -1.45 },
    shoulderR: { x: -0.70, y: 0.5 }, elbowR: { x: -1.50 },
  }),
  guardBoth: J({
    shoulderL: { x: -0.95 }, elbowL: { x: -1.15 },
    shoulderR: { x: -0.80 }, elbowR: { x: -1.35 },
  }),
  armsDown: J({
    shoulderL: { x: -0.10, z: 0.08 }, shoulderR: { x: -0.10, z: -0.08 },
    elbowL: { x: -0.15 }, elbowR: { x: -0.15 },
  }),
  // Archer block, right arm high across forehead, left across torso
  archerBlockR: J({
    shoulderR: { x: -1.90, z: 0.40 }, elbowR: { x: -1.30 },
    shoulderL: { x: -0.75, y: -0.55 }, elbowL: { x: -1.45 },
  }),
  // Reinforced block: right forearm blocks, left hand grabs right forearm
  reinforcedBlockR: J({
    shoulderR: { x: -1.05, z: 0.15 }, elbowR: { x: -1.20, y: 0.3 },
    shoulderL: { x: -0.85, y: -0.45 }, elbowL: { x: -1.35 },
  }),
  // Dump / kata garuma load: left hand high (throat), right hand low (hook)
  dumpLoad: J({
    shoulderL: { x: -1.55 }, elbowL: { x: -0.45 },
    shoulderR: { x: -0.35 }, elbowR: { x: -0.55 },
    spine: { x: 0.25 },
  }),
  dumpFinish: J({
    shoulderL: { x: -0.55 }, elbowL: { x: -0.25 },
    shoulderR: { x: -0.85 }, elbowR: { x: -0.35 },
    spine: { x: 0.35 },
  }, { y: -0.12 }),
  doubleShutoThroat: J({
    shoulderL: { x: -1.30, z: -0.30 }, elbowL: { x: -0.45 },
    shoulderR: { x: -1.30, z: 0.30 }, elbowR: { x: -0.45 },
  }),
  doubleFistDown: J({
    shoulderL: { x: -0.70 }, elbowL: { x: -0.40 },
    shoulderR: { x: -0.70 }, elbowR: { x: -0.40 },
    spine: { x: 0.18 },
  }),
  doubleCollarbone: J({
    shoulderL: { x: -1.35, z: -0.20 }, elbowL: { x: -0.75 },
    shoulderR: { x: -1.35, z: 0.20 }, elbowR: { x: -0.75 },
  }),
  doubleKidneyStrike: J({
    shoulderL: { x: -1.10 }, elbowL: { x: -0.60 },
    shoulderR: { x: -1.10 }, elbowR: { x: -0.60 },
    spine: { x: 0.15 },
  }),
  xGuardChest: J({
    shoulderL: { x: -0.80, z: 0.30 }, elbowL: { x: -1.20 },
    shoulderR: { x: -0.80, z: -0.30 }, elbowR: { x: -1.20 },
  }),
};

// ---------------------------------------------------------------------------
// Leg techniques (authored for RIGHT leg; left generated by mirror)
// ---------------------------------------------------------------------------
const LEGS_RIGHT = {
  frontKick: J({
    hipR: { x: -1.45 }, kneeR: { x: 0.20 }, ankleR: { x: 0.45 },
    hipL: { x: 0.06 }, kneeL: { x: 0.22 },
  }, { y: -0.03 }),
  sideKick: J({
    hipR: { x: -0.55, z: -0.95 }, kneeR: { x: 0.25 }, ankleR: { x: 0.3 },
    hipL: { x: 0.04 }, kneeL: { x: 0.25 }, spine: { z: 0.18 },
  }, { y: -0.03 }),
  kneeLift: J({
    hipR: { x: -1.35 }, kneeR: { x: 1.50 },
    hipL: { x: 0.05 }, kneeL: { x: 0.18 },
  }, { y: -0.02 }),
  jumpKick: J({
    hipR: { x: -1.55 }, kneeR: { x: 0.25 }, ankleR: { x: 0.5 },
    hipL: { x: -0.65 }, kneeL: { x: 1.35 },
  }, { y: 0.28 }),
  legLift: J({
    hipR: { x: -0.50 }, kneeR: { x: 0.95 }, ankleR: { x: 0.2 },
    hipL: { x: 0.03 }, kneeL: { x: 0.20 },
  }, { y: -0.04 }),
  stomp: J({
    hipR: { x: -0.85 }, kneeR: { x: 1.10 }, ankleR: { x: -0.3 },
    hipL: { x: 0.04 }, kneeL: { x: 0.20 },
  }, { y: -0.04 }),
};

// ---------------------------------------------------------------------------
// Assemble POSES: L/R variants generated by mirroring.
// ---------------------------------------------------------------------------
export const POSES = {};

for (const [name, pose] of Object.entries(STANCES_BASE)) {
  if (name.endsWith('L')) {
    POSES[name] = pose;
    POSES[name.slice(0, -1) + 'R'] = mirrorPose(pose);
  } else {
    POSES[name] = pose;
  }
}
for (const [name, pose] of Object.entries(ARMS_RIGHT)) {
  POSES[name + 'R'] = pose;
  POSES[name + 'L'] = mirrorPose(pose);
}
for (const [name, pose] of Object.entries(ARMS_BOTH)) {
  POSES[name] = pose;
  if (name.endsWith('R')) POSES[name.slice(0, -1) + 'L'] = mirrorPose(pose);
}
for (const [name, pose] of Object.entries(LEGS_RIGHT)) {
  POSES[name + 'R'] = pose;
  POSES[name + 'L'] = mirrorPose(pose);
}
