// Generates the per-keyframe timing map for one kata (docs/<kata>-timing.md).
// Every number comes from the real engine, so the map cannot drift from playback.
//
//   node tools/timing-map.mjs            # seisan -> stdout
//   node tools/timing-map.mjs seisan > docs/seisan-timing.md
import { POSES } from '../kata-viewer/js/poses.js';
import { buildTimeline, SECONDS_PER_BEAT, KIME_HOLD_BEATS } from '../kata-viewer/js/player.js';
import { loadKata } from './validate-data.mjs';

const DEFAULT_HOLD = KIME_HOLD_BEATS * SECONDS_PER_BEAT;
const s2 = (n) => n.toFixed(2);

// The source keyframes in the order buildTimeline consumes them, so the
// finalized list (which only ever *inserts* hold-end copies) maps back 1:1.
function sourceFrames(kata) {
  const out = [];
  let cursor = 0;
  for (const [idx, step] of kata.steps.entries()) {
    const beats = step.beats ?? 2;
    const dur = beats * SECONDS_PER_BEAT;
    for (const [ki, kf] of step.keyframes.entries()) {
      out.push({
        step, idx, ki, beats,
        first: ki === 0,
        authored: cursor + kf.t * dur,
        t: kf.t,
        parts: [kf.stance, ...(kf.arms || []), ...(kf.legs || [])].filter(Boolean),
        overrides: kf.overrides ? Object.keys(kf.overrides) : [],
        authoredEase: kf.ease,
        authoredHold: kf.hold,
      });
    }
    cursor += dur;
  }
  return out;
}

function rows(kata, timeline) {
  const src = sourceFrames(kata);
  const out = [];
  let i = 0;
  for (const [n, kf] of timeline.kfs.entries()) {
    if (kf.holdEnd) continue;
    const s = src[i++];
    const next = timeline.kfs[n + 1];
    const holdEnd = next && next.holdEnd ? next : null;
    const held = holdEnd ? holdEnd.time - kf.time : 0;
    const wanted = kf.hold ?? (kf.ease === 'kime' ? DEFAULT_HOLD : 0);
    out.push({
      ...s,
      time: kf.time,
      ease: kf.ease,
      easeSource: s.authoredEase ? 'set' : 'auto',
      held,
      wanted,
      clamped: held > 0 && wanted - held > 1e-6,
      travel: kf.time - s.authored > 1e-6,
      look: kf.lookYaw ? (kf.lookYaw > 0 ? 'left' : 'right') : '',
    });
  }
  return out;
}

function render(name, kata, timeline) {
  const L = [];
  const kfRows = rows(kata, timeline);
  L.push(`# ${kata.displayName || kata.name} — timing map`);
  L.push('');
  L.push('<!-- GENERATED by tools/timing-map.mjs. Do not edit by hand; regenerate after every');
  L.push(`     timing change:  node tools/timing-map.mjs ${name} > docs/${name}-timing.md  -->`);
  L.push('');
  L.push(`${timeline.steps.length} steps, ${s2(timeline.duration)} s at 1.00× (1 beat = ${SECONDS_PER_BEAT} s).`);
  L.push('');
  L.push(`Cite any row by pasting \`http://localhost:8420/?kata=${name}&t=<time>\` — the **t** column is`);
  L.push('exactly what the viewer\'s `t = … s` readout shows. Playback speed does not change these numbers.');
  L.push('');
  L.push('## Steps');
  L.push('');
  L.push('| # | id | start–end | beats | label | kiai | look |');
  L.push('|---|---|---|---|---|---|---|');
  for (const [i, st] of timeline.steps.entries()) {
    L.push(`| ${i + 1} | ${st.id} | ${s2(st.start)}–${s2(st.end)} | ${st.beats ?? kata.steps[i].beats ?? 2} | ${st.label} | ${st.kiai ? 'KIAI' : ''} | ${st.look || ''} |`);
  }
  L.push('');
  L.push('## Keyframes');
  L.push('');
  L.push('`ease` — how the frame is *arrived at*: `kime` snap, `soft` settle, `pass` flow through.');
  L.push('`(auto)` means the engine derived it; it is not written in the JSON.  ');
  L.push('`hold` — seconds frozen on this frame before the next move starts. `clamped` means the');
  L.push('requested hold did not fit in the gap (max half of it) and was cut.  ');
  L.push('`travel` marks a frame pushed to 25% into its step because it collided with the previous');
  L.push('step\'s last frame — that first quarter of the step is the step/turn into position.');
  L.push('');
  const zero = [];
  for (let i = 1; i < kfRows.length; i++) {
    if (kfRows[i].step === kfRows[i - 1].step && kfRows[i].time - kfRows[i - 1].time < 1e-6) zero.push(kfRows[i - 1]);
  }
  const clamped = kfRows.filter(r => r.clamped);
  if (zero.length || clamped.length) {
    L.push('## Warnings');
    L.push('');
    for (const r of zero) {
      L.push(`- **step ${r.step.id}, keyframe ${r.ki} is never seen** — it lands at ${s2(r.time)} s, the same`);
      L.push(`  instant as the next frame, because the following frame's \`t\` (${kfRows[kfRows.indexOf(r) + 1].t}) is at or inside the`);
      L.push('  25% travel window. Give the next frame a larger `t`, or more `beats` to the step.');
    }
    for (const r of clamped) {
      L.push(`- step ${r.step.id}, keyframe ${r.ki} at ${s2(r.time)} s: hold cut to ${s2(r.held)} s of the ${s2(r.wanted)} s asked`);
      L.push('  for (a hold may take at most half the gap to the next frame).');
    }
    L.push('');
  }
  L.push('| t (s) | step | kf | poses | ease | hold | notes |');
  L.push('|---|---|---|---|---|---|---|');
  for (const r of kfRows) {
    const notes = [];
    if (r.travel) notes.push(`travel from ${s2(r.authored)}`);
    if (r.clamped) notes.push(`hold clamped from ${s2(r.wanted)}`);
    if (r.look) notes.push(`look ${r.look}`);
    if (r.overrides.length) notes.push(`overrides: ${r.overrides.join(', ')}`);
    L.push(`| **${s2(r.time)}** | ${r.step.id} | ${r.ki} (t=${r.t}) | ${r.parts.join(' + ')} | ${r.ease}${r.easeSource === 'auto' ? ' (auto)' : ''} | ${r.held ? s2(r.held) : '—'} | ${notes.join('; ')} |`);
  }
  L.push('');
  return L.join('\n');
}

const name = (process.argv[2] || 'seisan').replace(/\.json$/, '');
const kata = loadKata(name + '.json');
process.stdout.write(render(name, kata, buildTimeline(kata, POSES)) + '\n');
